---
title: "Projet Transdev"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(xts)
library(lubridate)
library(dplyr)
library(tidyverse)
library(Metrics)
library(forecast)
library(tseries)
library(caschrono)
```

# Cluster 2 (le plus fréquenté)

```{r}
serie2 = df[,c("DAY", "LIGNE", "DATETIME", "HEURE")]
serie2 = serie2[ serie2$LIGNE %in% names(groupes.cah[unname(groupes.cah)==2]), ]
serie2[,"DATETIME"] = ceiling_date( serie2[,"DATETIME"], "hour")
serie2 = serie2 %>% count(DATETIME)

# Heures manquantes 
data_with_missing_times <- full_join(df2,serie2)

# Remplacer NA par 0
data_with_missing_times[is.na(data_with_missing_times)] <- 0
serie2 <- xts(data_with_missing_times[,-1], order.by=data_with_missing_times[,1])
```

```{r}
#serie2 %>% ggtsdisplay(main="")
ggtsdisplay(serie2, lag.max=400)

ggtsdisplay( serie2[1:1500], lag.max=400)
  
# On applique 2 fois la méthode des différences (on zomme sur les 1500 premières valeurs pour un meilleur apercu)
ggtsdisplay( diff( diff(serie2[1:1500], lag=24), lag=168 ), lag.max=400 )
```
```{r}
serie2 = ts(diff( diff(serie2, lag=24), lag=168 ),frequency=24)
```

```{r}
auto.arima(serie2)
```

```{r}
#model = tseries::arma(na.remove(serie2), order=c(1,0,0))

model = tseries::arma(na.remove(serie2), order=c(5,0,5))
plot(na.remove(serie2))
lines(model$fitted.values, col='red')

summary(model)
```

# Test de Ljung box
```{r}
Box.test(model$residuals, type="Ljung-Box")
```

```{r}
serie2_2 = ts(diff( diff(serie2[1:1500], lag=24), lag=168 ),frequency=24)
serie2_2 = ts( serie2[1:1500] )
```

```{r}
auto.arima(serie2_2)
```

```{r}
model = tseries::arma(na.remove(serie2_2), order=c(2,1,5))
plot(na.remove(serie2_2))
lines(model$fitted.values, col='red')

summary(model)
```


# Cluster 1 (le moins fréquenté)

```{r}
# Une serie par cluster
serie1 = df[,c("DAY", "LIGNE", "DATETIME", "HEURE")]
serie1 = serie1[ serie1$LIGNE %in% names(groupes.cah[unname(groupes.cah)==1]), ]
serie1[,"DATETIME"] = ceiling_date( serie1[,"DATETIME"], "hour")
serie1 = serie1 %>% count(DATETIME)

# Heures manquantes 
data_with_missing_times <- full_join(df2,serie1)

# Remplacer NA par 0
data_with_missing_times[is.na(data_with_missing_times)] <- 0
serie1 <- xts(data_with_missing_times[,-1], order.by=data_with_missing_times[,1])
```

```{r}
auto.arima(serie1)
```

```{r}
model = tseries::arma(na.remove(serie1), order=c(4,0,0))
plot(na.remove(serie1))
lines(model$fitted.values, col='red')

summary(model)
```
```{r}
plot(serie1)
```

# On remarque que le nombre maximal de validations dans ce cluster sur toute l'année est de 6, ce qui est très faible. D'ou la mauvaise prédiction.

# Test de Ljung box
```{r}
Box.test(model$residuals, type="Ljung-Box")
```

# Cluster 4 (moyennement fréquenté)

```{r}
serie4 = df[,c("DAY", "LIGNE", "DATETIME", "HEURE")]
serie4 = serie4[ serie4$LIGNE %in% names(groupes.cah[unname(groupes.cah)==4]), ]
serie4[,"DATETIME"] = ceiling_date( serie4[,"DATETIME"], "hour")
serie4 = serie4 %>% count(DATETIME)

# Heures manquantes 
data_with_missing_times <- full_join(df2,serie4)

# Remplacer NA par 0
data_with_missing_times[is.na(data_with_missing_times)] <- 0
serie4 <- xts(data_with_missing_times[,-1], order.by=data_with_missing_times[,1])
```

```{r}
serie4 = ts(diff( diff( serie4, lag=24 ), lag=168),frequency=24)
```


```{r}
auto.arima(serie4)
```

```{r}
model = tseries::arma(na.remove(serie4), order=c(5,0,2))
plot(na.remove(serie4))
lines(model$fitted.values, col='red')

summary(model)
```
# Test de Ljung box
```{r}
Box.test(model$residuals, type="Ljung-Box")
```

# Cluster 3 (très peu fréquenté)

```{r}
serie3 = df[,c("DAY", "LIGNE", "DATETIME", "HEURE")]
serie3 = serie3[ serie3$LIGNE %in% names(groupes.cah[unname(groupes.cah)==3]), ]
serie3[,"DATETIME"] = ceiling_date( serie3[,"DATETIME"], "hour")
serie3 = serie3 %>% count(DATETIME)

# Heures manquantes 
data_with_missing_times <- full_join(df2,serie3)

# Remplacer NA par 0
data_with_missing_times[is.na(data_with_missing_times)] <- 0
serie3 <- xts(data_with_missing_times[,-1], order.by=data_with_missing_times[,1])
```


```{r}
serie3 = ts(diff( diff( serie3, lag=24 ), lag=168),frequency=24)
```


```{r}
auto.arima(serie3)
```


```{r}
model = tseries::arma(na.remove(serie3), order=c(5,0,0))
plot(na.remove(serie3))
lines(model$fitted.values, col='red')

summary(model)
```

# Test de Ljung box
```{r}
Box.test(model$residuals, type="Ljung-Box")
```

